name: smokeapi
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  pedantic: ^1.10.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
